### PR TITLE
Fix: Add missing _navTooltip and nav button fields to course schema (fixes #94)

### LINKED ISSUE #94: Add missing _navTooltip to new schema
Tooltip API added in previous PR https://github.com/cgkineo/adapt-visua11y/issues/52

### PR DESCRIPTION
**Pull request by kirsty-hames**
Fixes #94 

Tooltip API added in previous PR https://github.com/cgkineo/adapt-visua11y/issues/52. Course schema wasn't updated.

Note, this hasn't been AAT tested.

### CODE REVIEW

**Comment by swashbuck** [comment]
Hi, @kirsty-hames . I've pushed a few changes for this and merged in the latest `master` branch. Seems to be working on Staging ( https://staging.kineoadapt.com ). Will you test this? You can use "Brad Test Course Jul 20" if you'd like.

Also, we should add the `_navLabel` property as well from #93 since that was approved and merged. Would you rather handle that one in a separate ticket or include it here?

**Comment by kirsty-hames** [comment]
> Also, we should add the `_navLabel` property as well from #93 since that was approved and merged. Would you rather handle that one in a separate ticket or include it here?

Thanks @swashbuck, I think thats fine to add here and just update the PR title?

**Comment by swashbuck** [comment]
@kirsty-hames Cool, I'll add that stuff, too.

**Comment by swashbuck** [comment]
@kirsty-hames Ok, the navigation button fields have been added as well.

**Pull request merged**
