### PR TITLE
issue/181 Styling fixes and reset alert

### PR DESCRIPTION
**Pull request by oliverfoster**
### Fixed
* notify styling to include title and body

### Added
* reset alert using notify api

requires https://github.com/adaptlearning/adapt-contrib-core/pull/182

### CODE REVIEW

**Review by joe-replin — APPROVED** [review]
aria-live assertive notification is being received in my testing. Great recommendation.

**Comment by RMurray89** [comment]
@oliverfoster - Thanks for this. The text is now rendered in the notify panel but it is below the visua11y settings. The order of the divs needs reversed so visua11y settings is below the text. 

image

**Comment by oliverfoster** [comment]
This is the fix: https://github.com/adaptlearning/adapt-contrib-core/issues/158
Released in this version of the core: https://github.com/adaptlearning/adapt-contrib-core/releases/tag/v6.11.0

**Comment by RMurray89** [comment]
> This is the fix: [adaptlearning/adapt-contrib-core#158](https://github.com/adaptlearning/adapt-contrib-core/issues/158) Released in this version of the core: https://github.com/adaptlearning/adapt-contrib-core/releases/tag/v6.11.0

Thanks, Oliver. I'll speak to our IT and see if we can get core updated.

**Pull request merged**
