### PR TITLE
performance, offlineStorage, debugging, _shouldSavePreferences

### LINKED ISSUE #7: cookie storage rules
Is there a potential issue with storing the selections in a cookie without informing users or at least making the client aware?
Not all Adapt content is built for internal client use, so not sure if this impacts the decision on whether cookies can be used without agreement. There isn't any personal data stored but not sure on the rules for The Cookie Law.

Could the data be saved to via `Adapt.offlineStorage` for use with SCORM or xAPI, or does it take up too much space for SCORM `cmi.suspend_data`?

### LINKED ISSUE #16: Default
Is it possible to have the 'Reset' status as the default initial view and then learners select the options to apply?

### LINKED ISSUE #17: Sluggish behaviour in Safari and iOS
The filter that is applied to images is causing the slowdown on Mac Safari & Safari OS. See line 24 of modifiers.less

needs:

```
transform: translateZ(0); /*for older browsers*/
will-change: transform;
```

### LINKED ISSUE #18: Visua11y settings
Options in Visua11y settings pop-up, can get confused. Noted behaviour:

New projects appear to have all options preselected (needs confirming)

De-selecting options sometimes aren't remembered. User needs to deselect one option, close. Reopen deselect another option, then close etc

### LINKED ISSUE #19: Debugging Visu11y CSS
Suggest changing the visua11y modified CSS to building its own selectors / stylesheet rather than injecting new css to aid debugging in complex courses.

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #7 
fixes #16 
fixes #17 
fixes #18 
fixes #19

### Fixes
* performance issue with render
* moved to offlineStorage from cookie
* used separate stylesheet rather than stylesheet overrides
* allowed the preferences not to be saved by using `_shouldSavePreferences: false`

### CODE REVIEW

**Review by StuartNicholls — APPROVED** [review]
Looks good, suggest removing that last selector..

```
.has-bg-image > * {
  filter: invert(var(--visua11y-invert));
}
```
     
     ..once the background images in adapt are handled in their own div

**Review by guywillis — CHANGES_REQUESTED** [review]
I think there's a bug with the 'no background images' toggle. Enabling the option can render some interactions, most notably the narrative, unusable to mouse users if there's no alt text defined on the images.

Edit: I realise now that the indicators can be used to go navigate through the items but it's not entirely clear. 

Additional stylesheet is a huge plus

**Comment by oliverfoster** [comment]
That's not something I can prevent @guywillis
When would a narrative not have alt text in practise?

**Comment by guywillis** [comment]
> That's not something I can prevent @guywillis When would a narrative not have alt text in practise?

For imagery that doesn't add anything meaningful to the text - I'd imagine this to be quite common.

Another thought.. should the 'No background images' label be amended to something that includes 'foreground' images without alt text? Something along the lines of 'Show only contextual imagery'

**Comment by StuartNicholls** [comment]
For me, its functioning correctly as the images are non-intreractive. Suggest updating narrative to work better without images

**Comment by StuartNicholls** [comment]
Hide 'decorative images' ?

**Comment by oliverfoster** [comment]
I can't include narrative images that have no alt text, without making an exception in visua11y. I don't want to specify an exception for each graphic instance which should always be shown with/without alt text. Here we're just using the alt text availability as a flag for foreground images. There is a separate ticket to mark up foreground and background images independently of the alt text but that's not included in these work.  https://github.com/adaptlearning/adapt_framework/issues/3164

**Comment by StuartNicholls** [comment]
Agreed, sort of makes sense the Narrative plug-in should really work without images anyway.

**Review by guywillis — APPROVED** [review]

**Pull request merged**
