### PR TITLE
Adding heading semantics for section headers

### PR DESCRIPTION
**Pull request by joe-replin**

### CODE REVIEW

**Comment by joe-replin** [comment]
#28

**Comment by oliverfoster** [comment]
The headings should start at 1 for all dialogs and documents.

**Review by kirsty-hames — COMMENTED** [review]
Good spot!
Just to query the `aria-level="3"`, I know we typically reset titles to '1' as a popup is a separate modal. Visually doesn't have a `notify-heading` however, only a `description` so we don't have that initial `aria-level="1"` title. I can see why we have '3' as these are category titles but just querying whether these should be '1'?

**Comment by oliverfoster** [comment]
It's about how the screen reader controls work. Users rely on the heading levels to see the structure of a modal.
image

Ref: https://www.freedomscientific.com/SurfsUp/Navigating.htm

**Comment by kirsty-hames** [comment]
> It's about how the screen reader controls work. Users rely on the heading levels to see the structure of a modal/document. image
> 
> Ref: https://www.freedomscientific.com/SurfsUp/Navigating.htm

I agree, that's what I was getting at but wasn't sure. Thanks for confirming.

**Comment by joe-replin** [comment]
Got it. Well explained. If we ever plan on adding a top-level heading to the dialog, then the numbers can be readjusted. I'll move them to level 1.

**Review by kirsty-hames — APPROVED** [review]

**Review by oliverfoster — APPROVED** [review]

**Pull request merged**
